# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'jobconnect.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.openButton = QtWidgets.QPushButton(self.centralwidget)
        self.openButton.setGeometry(QtCore.QRect(319, 0, 121, 32))
        self.openButton.setObjectName("openButton")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(370, 240, 411, 231))
        self.textEdit.setObjectName("textEdit")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(380, 210, 58, 16))
        self.label.setObjectName("label")
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(20, 160, 256, 192))
        self.listWidget.setObjectName("listWidget")
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        self.captureJobs = QtWidgets.QPushButton(self.centralwidget)
        self.captureJobs.setGeometry(QtCore.QRect(320, 40, 111, 32))
        self.captureJobs.setObjectName("captureJobs")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 24))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Job Connect Automator"))
        self.openButton.setText(_translate("MainWindow", "Open Browser"))
        self.textEdit.setMarkdown(_translate("MainWindow", "I hope this email finds you well.  I just recently saw a posting for a\n"
"{job_title} position at {company} + and would love to learn more.  My\n"
"experience with React.js, C#, and Java feels like a great fit for the\n"
"role\\n\\nCould you tell me more about the software development team and what\n"
"it\'s like to work for the company?I believe you would have great insight as a\n"
"{title} for {company}.\\nI appreciate any information you could provide, looking\n"
"forward to hearing from you!\n"
"\n"
""))
        self.label.setText(_translate("MainWindow", "Email"))
        __sortingEnabled = self.listWidget.isSortingEnabled()
        self.listWidget.setSortingEnabled(False)
        item = self.listWidget.item(0)
        item.setText(_translate("MainWindow", "New Item"))
        self.listWidget.setSortingEnabled(__sortingEnabled)
        self.captureJobs.setText(_translate("MainWindow", "Search Jobs"))
